### ISSUE TITLE
Share profile link by QR code

### ISSUE THREAD

**Issue by urdadx** [urdadx/librelinks#25]
Separate the share modal into two togglable tabs.  Use [Radix UI Tabs Component](https://www.radix-ui.com/themes/docs/components/tabs) for this.

One tab is for sharing by link, and the other by QR code.
Allow the user to download the QR code.

![image](https://github.com/urdadx/librelinks/assets/70736338/be025b58-526a-426a-bb0f-e183bb880afa)

**Comment by NewtonFernandis** [comment]
Hey @urdadx , I will work on this. Please assign this issue to me.

**Comment by urdadx** [comment]
Hey @NewtonFernandis.. I will assign this issue to you.

Also, I've updated the issue description. Please check it out.

Make sure to create a new branch for the pull-request 

Let me know if you have any questions.

**Comment by NewtonFernandis** [comment]
### Something like this is okay?
<img width="652" alt="Screenshot 2023-09-02 at 8 31 46 PM" src="https://github.com/urdadx/librelinks/assets/121332168/737076da-0a95-42e7-98c6-c9e950cf6ec9">

**Comment by urdadx** [comment]
this is perfect @NewtonFernandis
