### ISSUE TITLE
Twitter, Medium, Instagram and more icons missing

### ISSUE THREAD

**Issue by PriyansuMaurya** [urdadx/librelinks#26]
![image](https://github.com/urdadx/librelinks/assets/101447544/0dc1fae4-e2e2-4392-a670-adf537e40603)

**Comment by urdadx** [comment]
I am using a free SVG API to create the icons. An incorrect spelling of a particular website name in the URL might cause this.
Example: medium.com instead of Medium.com or incorrectly spelling Twitter.
 
Working on a fix
