### ISSUE TITLE
feat : shout out tweet link

### ISSUE THREAD

**Issue by PriyansuMaurya** [urdadx/librelinks#27]
![image](https://github.com/urdadx/librelinks/assets/101447544/8108d3ac-9592-46e8-8efa-f795a160b512)

Instead of directing users to https://twitter.com/, why not send a default message when redirecting them? This will increase the chances of sharing it on social media. We should implement this not only for Twitter but also for other social media platforms.

Click on this link: <a href="https://twitter.com/intent/tweet?text=Librelinks%20is%20seriously%20impressive!%20%F0%9F%91%8F%20A%20huge%20shoutout%20to%20%40NerdyProgramme2%20for%20this.%20%0A%0AFrom%20now%20on,%20you'll%20see%20me%20sharing%20this%20wherever%20I%20can.%0A%0ACheck%20it%20out%3A%20https%3A//librelinks.vercel.app/priyanshu%F0%9F%9A%80%20">Share on Twitter</a>

We can also use this link to generate a shareable link: https://www.sharelinkgenerator.com/

**Comment by urdadx** [comment]
Great idea @PriyansuMaurya . Feel free to send a pull request if you'd like to work on it.

**Comment by PriyansuMaurya** [comment]
Yeah, Sure.

**Comment by urdadx** [comment]
Great. Create a new branch for a new pull request with the feature you want to add. 
For example, this issue's PR can be named _**shout-out-tweek-link**_ .

I will be updating the repo with proper contribution guidelines. I'm new to open-source. Am still learning and figuring things out.  If you have any ideas on how I can make the repository more accessible for new contributors, I'm all ears.

**Comment by PriyansuMaurya** [comment]
> I will be updating the repo with proper contribution guidelines. I'm new to open-source. Am still learning and figuring things out. If you have any ideas on how I can make the repository more accessible for new contributors, I'm all ears.

Certainly, I will try to help you as much as I can. In the meantime, you can check out this repository, which is ideal for learning how to do project open source:

https://www.linkshub.dev/

**Comment by urdadx** [comment]
Hey @PriyansuMaurya, thank you for working on this issue. But correct me if am wrong. The only change you made was to delete Twitter  URL and replace it with an empty string. I don't think this would solve the issue.

See screenshot below👇

![image](https://github.com/urdadx/librelinks/assets/70736338/5cb45505-d281-428c-ae5f-f41919a9ca7f)

**Comment by PriyansuMaurya** [comment]
You are correct, actually it was my mistake. Now, I have fixed it.

![image](https://github.com/urdadx/librelinks/assets/101447544/26512d8a-caf1-411f-87b3-03dbd1a8f71c)

**Comment by PriyansuMaurya** [comment]
@urdadx, one more thing, always squash and merge the pull request, else your commits will be flooded with unnessary commits.

![image](https://github.com/urdadx/librelinks/assets/101447544/c226331e-2223-47ce-bf2f-8fa47308de4a)

You have done this mistake in the previous pull request.

![image](https://github.com/urdadx/librelinks/assets/101447544/da1ed37d-7c63-4c76-9239-c9743cb109e7)

**Comment by urdadx** [comment]
thank you for the heads up @PriyansuMaurya..Am learning alot
