### ISSUE TITLE
Toast Loading issue Bug

### ISSUE THREAD

**Issue by ameyabavkar** [urdadx/librelinks#29]
So i'm trying to change my information and it is working fine but the apply changes toast is not disappearing after the sometime and keeps showing on the website
![image](https://github.com/urdadx/librelinks/assets/65841021/52d6cbb8-30d8-4879-beef-d733d492e333)
I would like to solve this issue
Great site by the way

**Comment by urdadx** [comment]
Hi @Ameya02, thank you for contributing to this project.
Unfortunately, I was already working on a  fix for this. Just pushed it to production minutes ago. 

Can you test and confirm if it works?

You are welcome to work on other [open issues ](https://github.com/urdadx/librelinks/issues/)

**Comment by ameyabavkar** [comment]
Yes It working correctly now
