### ISSUE TITLE
 Format all files with Prettier 

### ISSUE THREAD

**Issue by NewtonFernandis** [urdadx/librelinks#31]

**Comment by NewtonFernandis** [comment]
Hey @urdadx, I feel the projects need to be formatted.

**Comment by urdadx** [comment]
Hey @NewtonFernandis, I firmly believe so, too. 
However, I honestly do not know how to do this properly.

I have no experience maintaining an open-source project and there's a lot I have to learn.
 Would be grateful if you could work on this.

**Comment by NewtonFernandis** [comment]
Yeah, I will work on this @urdadx You can assign this to me.

**Comment by urdadx** [comment]
Assigned

**Comment by NewtonFernandis** [comment]
@urdadx I will also configure this project with `husky` with `pre-commit` hook so that every commit is automatically formatted.
