### ISSUE TITLE
Open Graph (OG) Image generation

### ISSUE THREAD

**Issue by urdadx** [urdadx/librelinks#34]
Create OG images for various social media platforms [Learn more here](https://vercel.com/docs/functions/edge-functions/og-image-generation/og-image-examples)

[Video on OG images 
](https://youtu.be/6rYzM_oWi7A?si=2gDnsKQl00WjCsok)

**Comment by PriyansuMaurya** [comment]
Saw your new commit related to this issue

![image](https://github.com/urdadx/librelinks/assets/101447544/b186d0fd-e9f1-4e65-8517-8bfcc7f1d170)


![image](https://github.com/urdadx/librelinks/assets/101447544/21658255-96f0-4798-8ae9-22cf68e30788)

![image](https://github.com/urdadx/librelinks/assets/101447544/d7954c94-9b53-41eb-be95-f014ece3d26c)

Working okay on WhatsApp and Signal

![Screenshot (320)](https://github.com/urdadx/librelinks/assets/101447544/2e4d20f5-8ae7-4a4b-af37-6d57cf547b1a)

![Screenshot (319)](https://github.com/urdadx/librelinks/assets/101447544/7e0e0bc4-df39-4b44-818b-efb22ac3245c)



If you want, I can work on this.

**Comment by urdadx** [comment]
You can continue working on it. Use [this website](https://og.uneed.best/) to generate a nice OG image or you can design one yourself.
