### ISSUE TITLE
Bug: Upload pic functionality is not working correctly

### ISSUE THREAD

**Issue by PriyansuMaurya** [urdadx/librelinks#39]
When I click on the button to upload a profile photo, it just shows a toaster notification instead of opening the window to select the image.

![image](https://github.com/urdadx/librelinks/assets/101447544/7a532f78-df0c-4168-bc41-d1c7ed149050)

![image](https://github.com/urdadx/librelinks/assets/101447544/8b4aeff8-9748-4c0f-9d4b-d9d20130be82)

#### Page : https://librelinks.vercel.app/admin/settings

**Comment by urdadx** [comment]
I don't really understand this..can you elaborate further or upload a video/gif demo

**Comment by PriyansuMaurya** [comment]
https://github.com/urdadx/librelinks/assets/101447544/829f8102-863a-4867-97de-17c889fc19fb

**Comment by urdadx** [comment]
Thanks for clarifying the issue. 
What would you like to see happen?

Am thinking of making the button **disabled** or displaying a **warning** toast when nothing is uploaded.

**Comment by urdadx** [comment]
I've pushed a fix for this. Try it out and let me know if the issue still persists.

If you have any suggestions, you can share them as well.

**Comment by PriyansuMaurya** [comment]
Now its working fine.
