### ISSUE TITLE
Bug : Not able to log in via Google

### ISSUE THREAD

**Issue by PriyansuMaurya** [urdadx/librelinks#40]
The first time I logged in via GitHub, today I signed out (just for checking), and I logged back in. Then I encountered this issue: all social media and links were not getting fetched; I could only see the loading skeleton.

This issue occurred both on the actual page and the admin page.

![image](https://github.com/urdadx/librelinks/assets/101447544/7bdc1b3a-e8c6-4541-ad9e-3775bd6068f6)

![image](https://github.com/urdadx/librelinks/assets/101447544/b5a7c050-34be-4ece-8a3a-8eb75f144a2e)

To address this problem, I thought, 'Let's delete the account and create it again.' However, after deleting it, I am now unable to sign up using both GitHub and Google.

Note: I cannot provide more screenshots as I am unable to sign up to demonstrate the issue.

**Comment by urdadx** [comment]
> ![image](https://user-images.githubusercontent.com/101447544/266109082-7bdc1b3a-e8c6-4541-ad9e-3775bd6068f6.png)
From this screenshot, I can see you're signed in to another account, is this actually the case or this is just a random screenshot for demo purposes
>

**Comment by urdadx** [comment]
I will investigate this issue on my side. In the meantime, can you clear your cookies or try signing in using another browser or incognito mode? 

Also, send  a screenshot of your browser console and Network tab when you try signing in with both Google and Github.

**Comment by PriyansuMaurya** [comment]
> I will investigate this issue on my side. In the meantime, can you clear your cookies or try signing in using another browser or incognito mode?

I tried all the above options before reporting the issue, but it's still not working.

> Also, send a screenshot of your browser console and Network tab when you try signing in with both Google and Github.

Certainly.

Before clearing cache:

https://github.com/urdadx/librelinks/assets/101447544/8ab7cb50-5c9a-4d45-8bb5-7184a172b706

After clearing cache:

https://github.com/urdadx/librelinks/assets/101447544/b8da3d53-7413-4646-bad6-f40bf25168cb

**Comment by urdadx** [comment]
I pushed a fix for this...Test and see if it works for you.

**Comment by PriyansuMaurya** [comment]
Now, it works fine both for GitHub and Google, you can close this issue.
