### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by PriyansuMaurya** [urdadx/librelinks#41]
When someone creates a pull request, they currently receive a blank template, which requires them to manually input details like issue numbers and screenshots.

![image](https://github.com/urdadx/librelinks/assets/101447544/4bcf02d5-e255-4af4-94e3-22573e617c5a)

By implementing a pull request template, we can streamline this process. Contributors won't need to think about what to include; they can simply provide the necessary information.

![image](https://github.com/urdadx/librelinks/assets/101447544/a3211b4f-2b3e-48e1-a104-a1e69dba605a)

Additionally, we could also consider adding 1-2 issue templates. These would help create clear and tailored issue reports for various purposes.

I would like to work on this

**Comment by urdadx** [comment]
This is a good idea. I have assigned this to you.
