### ISSUE TITLE
[Bug]: Links Page is not responsive 

### ISSUE THREAD

**Issue by PriyansuMaurya** [urdadx/librelinks#49]
### Description

This is how the mobile version of the links page should appear, but in reality It is not responsive for either tablets or mobile phones. 

![image](https://github.com/urdadx/librelinks/assets/101447544/90c6595b-1c6a-4dd6-b7ff-38d6995d9117)

This is precisely what I would like to fix.

### Screenshots (if applicable)

You can also watch a video demonstrating the same here:

https://github.com/urdadx/librelinks/assets/101447544/6cce4212-0ac9-4440-9be5-c560f5cbe72d

### Affected Browser

Microsoft Edge

### Checklist

- [X] Checked for similar issues
- [X] Willing to work on this issue (optional)

**Comment by urdadx** [comment]
Apologies for attending to this late. I've been busy with school work

This would be a great improvement. I have assigned this issue to you

**Comment by PriyansuMaurya** [comment]
Hey there, @urdadx,

Please add LibreLinks to Hacktoberfest 🌟

Benefits:
- Increased contributions
- Community growth
- Project recognition

Here's how you can do it:

![image](https://github.com/urdadx/librelinks/assets/101447544/67bd786d-a306-4690-be7b-746951ec0818)

For more information, visit:

https://hacktoberfest.com/participation/

Example repo : https://github.com/rupali-codes/LinksHub
