### ISSUE TITLE
[Feature]: Replace toast notification library

### ISSUE THREAD

**Issue by urdadx** [urdadx/librelinks#52]
### Description

Replace [react-hot-toast](https://react-hot-toast.com/)  with [Sonner](https://sonner.emilkowal.ski/) . Sonner aligns more with the design and aesthetic of the site

### Checklist

- [X] Checked existing issues
- [ ] Willing to contribute (optional)

**Comment by ameyabavkar** [comment]
I will work on this

**Comment by urdadx** [comment]
Hey @Ameya02 , I have assigned this to you
