### ISSUE TITLE
a

### ISSUE THREAD

**Issue by fediralydev** [urdadx/librelinks#57]
a

**Comment by urdadx** [comment]
I think the problem might come from this👇.
![image](https://github.com/urdadx/librelinks/assets/70736338/2deb7f0e-32fc-46d4-9a76-c24e9710595c)


 The second callback URL redirects to the home page. Make sure to delete it

**Comment by fediralydev** [comment]
same problem : check : https://drive.google.com/file/d/1GWwMNklvuyqGzYC4ETNHKWQRh9HvW7ot/view?usp=sharing

**Comment by urdadx** [comment]
No. I said delete the URL 2 from your Authorized Redirect URIs. After that, try redeploying the website on Vercel

**Comment by fediralydev** [comment]
i make what ou say now but the smae problem and this problem its not just google its google and github same problem but look in localhost  its working : https://drive.google.com/file/d/1yhAlju55tpR2zbawmHNHv4du2OXquy3Y/view?usp=sharing

**Comment by fediralydev** [comment]
can you help please or  i think i need configure in vercel??
